# Generated by Django 3.0b1 on 2019-11-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_planner_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bill_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
