# Generated by Django 3.0.5 on 2020-04-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="outgoing",
            field=models.BooleanField(default=True),
        ),
    ]
